type Message {
  _id: ID!
  author: String!
  content: String!
}

input MessageInput {
  author: String!
  content: String!  
}

type Query {
  messages: [Message!]!
  message (id:ID!): Message! 
}

type Mutation {
  createMessage(data:MessageInput!): Message!
  updateMessage(id:ID!, data:MessageInput!): Message!
  deleteMessage(id:ID!): Boolean!
}

# type Subscription {}